/**********************************************************************
Name:  GeDA_Activities_DAO
Copyright © 2016
======================================================
======================================================
Purpose:  Used to store all queries related to the 
          Activities object

-------                                                             
======================================================
======================================================
History                                                            
-------                                                            
VERSION      AUTHOR                DATE             DETAIL             Description
   1.0      Mark Cook 		    14/03/2017          
***********************************************************************/ 
public with sharing class GeDA_Activities_DAO extends GeDA_SObject_DAO {


}