/**********************************************************************
Name:  GeEF_Exception_DAO
Copyright © 2016
======================================================
======================================================
Purpose:  Used to store all queries related to the 
          Exceptions object

-------                                                             
======================================================
======================================================
History                                                            
-------                                                            
VERSION      AUTHOR                DATE             DETAIL             Description
   1.0      Mark Cook 		    14/03/2017          
***********************************************************************/ 
public with sharing class GeEF_Exception_DAO extends GeDA_SObject_DAO {
}