/******************************************************************
 Name:  GeEF_Exception_I
 Copyright © 2017
 ======================================================
======================================================
Purpose:  Interface method for the exception Framework
-------                                                             
======================================================
======================================================
History                                                            
-------                                                            
VERSION      AUTHOR                DATE             DETAIL             Description
   1.0    	Mark Cook 		    21/08/2017          
***********************************************************************/  
public interface GeEF_Exception_I {

	  /* this method should be used to determine the 
	  *  logic required for processing the exceptions
      * */
      void processExceptions();
}